name: Build roadmap.json

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch open issues
        run: |
          curl -s \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/Telcoin-Association/telcoin-network/issues?state=open&per_page=50" \
            | jq '[.[] | {number, title, url: .html_url, updated_at}]' > roadmap.json
          cat roadmap.json

      - name: Commit roadmap.json
        run: |
          git config user.name  "roadmap-bot"
          git config user.email "roadmap@users.noreply.github.com"
          git add roadmap.json
          git commit -m "update roadmap.json" || echo "No changes"
          git push
