name: Build roadmap.json (via PR)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # once every 24 hours at midnight UTC

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Fetch open issues (REST API)
        run: |
          curl -s \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/Telcoin-Association/telcoin-network/issues?state=open&per_page=100" \
            | jq '[ .[] | select(.pull_request | not) | {number, title, url: .html_url, updated_at} ]' > roadmap.json
          echo "Preview roadmap.json:"
          head -n 20 roadmap.json || true
          test -s roadmap.json

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: update roadmap.json"
          title: "chore: update roadmap.json"
          body: "Automated update to roadmap.json from open GitHub Issues."
          branch: automation/roadmap-json
          base: main
          add-paths: |
            roadmap.json
          labels: |
            automation
